### ISSUE TITLE
Labe "clone" it self with open are new project in current window

### ISSUE THREAD

**Issue by Vakhrushev** [drinchev/project-label#1]
https://i.imgur.com/YpzFfW7.png

intellij 2017.1.*

**Comment by drinchev** [comment]
Seems that I can't reproduce this with my WebStorm. Anyway will check with IntelliJ CE

**Comment by tnguven** [comment]
This happens when you open a new project or folder to the current one but not all the time :)

**Comment by drinchev** [comment]
The Preferences dialog was added to the preferences pane, so this should've been fixed now.
