### ISSUE TITLE
Optionally display the project label as a background image of the whole window

### ISSUE THREAD

**Issue by simschla** [drinchev/project-label#16]
When working with multiple open windows in IntelliJ, it is often hard to tell which window is which, e.g. when switching windows using mission control because the label in the status bar is not easily readable. 

When discussing with my colleagues at work, several of them mentioned it would be very helpful, if one could optionally have the project label in a much bigger way as a background image of the whole editor window. 

Since I would love to have that too, I've prototyped a bit and am fairly confident, that this would improve the UX in such cases.

@drinchev Would you be OK to including that in the project-label plugin?
Then I'll go ahead and polish things up to create a PR.

My current implementation looks like this:
 
![SCR-20230407-ithd](https://user-images.githubusercontent.com/71494/230563001-756348c7-3e74-4bd1-b5b0-a68e02cbe2a7.png)
![SCR-20230407-itjy](https://user-images.githubusercontent.com/71494/230563021-5c442ddd-df47-43bb-8422-58e6a975df43.png)

**Comment by drinchev** [comment]
Sounds like a cool feature :)

It would be okay if we include this feature.

My feedback is regarding the settings form : 

From UX perspective, maybe we can move the `hidden` option form Position to some sort of "Enabled" checkbox close to the Background.

Also I'm not sure if the `Position` should be radio buttons or a dropdown. I was looking at some UI elements from IntelliJ and it looks like they use icons for those.

![image](https://user-images.githubusercontent.com/202919/230565364-b8f0dc2c-eecb-4aa3-a978-6f76dcaae3d8.png)

**Comment by simschla** [comment]
Cool, thanks for the feedback regarding UX for the preferences. I'll certainly look into those UI elements. You happen to have a pointer to where these icons are used in IntellijJ's codebase?

**Comment by simschla** [comment]
BTW: As you can see on my screenshots above, the status bar label is not too big on new UI in my code. (This is without #15 )

Is there anything I've changed in the rendering code, that fixes this?

**Comment by drinchev** [comment]
> As you can see on my screenshots above, the status bar label is not too big on new UI in my code. (This is without https://github.com/drinchev/project-label/pull/15 )

Bummer, I guess I checked locally and all of the IDEs that I tested ( Including WebStorm ) had the very same big label. Based on the code I noticed that it takes the full height of the status bar and in the new UI the status bar's height is larger.

Anyway I hope the new release (v1.1.1) won't fix it for me and break it for someone else. Let's see.

>  You happen to have a pointer to where these icons are used in IntellijJ's codebase?

There's an API for that I hope. You can check all icons in the platform in https://jetbrains.design/intellij/resources/icons_list/

**Comment by simschla** [comment]
How about something along these lines?

![SCR-20230408-jcox](https://user-images.githubusercontent.com/71494/230710422-fd9b4094-cb54-4b98-9eb1-2647f2e33a2c.png)
![SCR-20230408-jdci](https://user-images.githubusercontent.com/71494/230710427-8dafc855-809c-4fd6-a6a0-aa8efc55be85.png)

**Comment by drinchev** [comment]
Looks awesome! Thanks.

Btw, should this be a global setting or project setting or both? 

In case I want all my projects to have this label in the background, I will have to enable this for each project or globally?

The project label has some global settngs for the font size and font name, and per project for the color. So maybe we can follow similar logic.

**Comment by simschla** [comment]
Currently it's on project level only. If you feel like offering this option on application level, that would certainly also make sense.

**Comment by drinchev** [comment]
Hmm.. 

I lean more towards global setting, since when you configure once the opacity and the position, you would expect the very same behaviour when you switch between projects.

Do you mind continuing this conversation in the PR? Maybe once I test it, I will have better feeling about the answer 😄

**Comment by intfoo** [comment]
This is a very good idea, I'm looking forward to it

**Comment by simschla** [comment]
Published in `1.2.0`.
