### ISSUE TITLE
Label text is gone. 

### ISSUE THREAD

**Issue by tnguven** [drinchev/project-label#2]
Did anyone get this issue before. Maybe I have change some settings!!

![screen shot 2017-06-01 at 09 41 39](https://cloud.githubusercontent.com/assets/6273412/26671790/b2ca91cc-46ae-11e7-8ae6-420a1d4e54bf.png)

**Comment by drinchev** [comment]
Hmm.. Can you try on an empty project and see if it works?

**Comment by drulmc** [comment]
Yeah i'm having the same issue, the label appears but no text.

**Comment by daedlock** [comment]
Same issue here in 2017.3

**Comment by drinchev** [comment]
Can you guys re-check this issue? I released v1.0 of this plugin, which hopefully could've fixed the issue ( because of selecting an available default font ).

**Comment by drinchev** [comment]
I'm going to close this, because of inactivity
