### ISSUE TITLE
Label text off center

### ISSUE THREAD

**Issue by sinnbeck** [drinchev/project-label#3]
Shouldn't it be centered? It seems to always be a bit off center.
I am using PHPStorm 2018.2

**Comment by drinchev** [comment]
This should've been fixed in the latest release 1.0. Tell me if you have any other problems.

**Comment by ddnexus** [comment]
If you mean "horizontally centered" it looks fixed, but for "vertically centered" it is still quite erratic. 
You can have quite different bottom and top spaces. Also, being in a box, the top and bottom spaces are inevitably very different when it is all caps.

Maybe a baseline-shift value (range -10 to +10 for example) could fix that.

Thanks

**Comment by drinchev** [comment]
Hey @ddnexus can you post a screenshot what do you mean with the Font name / font size?

**Comment by drinchev** [comment]
I'll close this issue, since the last activity was a long time ago.
