### ISSUE TITLE
Hardcoded label font size

### ISSUE THREAD

**Issue by ddnexus** [drinchev/project-label#4]
The `TextAttribute.SIZE` looks hardcoded at 8. It is extremely small on my laptop. 

A setting to choose font/weight/size would be great!

Modifying it in the src file looks trivial but I have no idea about how to compile it (I use it in RubyMine and I don't know anything about Java). Is there any quick way to compile it without Java knowledge? :) Thanks.

**Comment by drinchev** [comment]
This was fixed in the current release 1.0. Tell me if you have more problems.
