### ISSUE TITLE
doesnt work in "new u"i updated in latest webstorm

### ISSUE THREAD

**Issue by ermaneng** [drinchev/project-label#9]

**Comment by ermaneng** [comment]
project label is a great plug in if you work with many projects. 
jetbrains introduced a new ui in settings/appearance. so the layout changed if you use new ui. project label doesn't work with this new ui

version: WebStorm 2022.3.2

![2023-02-03 11_07_56-Settings](https://user-images.githubusercontent.com/6246331/216546724-a673c3da-56d5-44b3-86c0-1296b807dbfc.png)

**Comment by drinchev** [comment]
Hi @ermaneng sorry for the late reply.

On 2023.1 it looks even worse :

![image](https://user-images.githubusercontent.com/202919/228462842-d0059208-1848-4629-b69f-eee06a3c575c.png)

I plan to update the plugin some time in April, however any help is appreciated. My plan was to move to Kotlin and use the official Plugin framework by JetBrains.

**Comment by ermaneng** [comment]
great news. it's one of the best plugin for productivity. sometimes i switch between 3-5 projects a day so it keeps me focus while working. been looking for update.
